### PR TITLE
template of README with some updated content waiting someone to merge…

### PR DESCRIPTION
**Pull request by nikomakr**
I woked on template of README as we agreed on with some updated content waiting someone to merge it to main branch and Chiamaka you need to add the User Acceptance Criteria we agreed on and the link of Figma with prototype(s).

### CODE REVIEW

**Comment by nikomakr** [comment]
I created a template of README  with some updated content waiting someone to merge it to main branch and Chiamaka to add the User Acceptance Criteria we agreed on and the link of Figma prototype(s)

**Review by nikomakr — COMMENTED** [review]
I created a template of README with some updated content waiting someone to merge it to main branch and Chiamaka to add the User Acceptance Criteria we agreed on and the link of Figma prototype(s)

**Comment by nikomakr** [comment]
Can someone merge it on main please?

**Review by d-sholaakanbi — APPROVED** [review]
Nice!

**Pull request merged**
